### ISSUE TITLE
Suggestion: Preview loading screen

### ISSUE THREAD

**Issue by Xetheon** [TeamMidnightDust/CustomSplashScreen#1]
Dark Loading Screen has this really nice feature that allows you to preview the loading screen directly from its in-game config screen. While it isn't a big deal, it _is_ really satisfying to be able to preview each and every tiny little change made without ever needing to restart the game.

**Comment by slushie0** [comment]
While I agree with this, until it gets added you can preview the screen by going to resource packs and adding or removing one.
