### ISSUE TITLE
Not Importing Custom Background Image

### ISSUE THREAD

**Issue by Monorange** [TeamMidnightDust/CustomSplashScreen#11]
Hello!, when i tried to import my own custom image into the mod config, the image was the same

![image](https://user-images.githubusercontent.com/100101443/170844321-4a437065-7a3c-483a-80a1-234cff63d69d.png)

![image](https://user-images.githubusercontent.com/100101443/170844370-be7acb83-ffe0-4969-a74f-416e5edda8c0.png)

The route of the backgroudn image was the same (background) was the same.

And they were both the same size / resolution (960x540), Any help?

**Comment by Motschen** [comment]
It looks like you replaced the image in the jar, but you have to replace the image in the .minecraft/config/customsplashscreen directory

**Comment by Monorange** [comment]
Ohh i see, Alright, Thanks!

**Comment by Motschen** [comment]
The files in the jar are just the example images that are copied to the config folder on initial load, you can ignore them.
