### ISSUE TITLE
Mod conflict with multiconnect

### ISSUE THREAD

**Issue by DangerMage** [TeamMidnightDust/CustomSplashScreen#14]
Log: https://paste.ee/p/A4xpX

Ignore the broken narrator libraries, that is a bug with multimc at this time.

Using the latest version of multiconnect and custom splash screen causes the game to look like it's infinity loading the game while flickering the menu of multiconnect's buttons which also turn to squares.

Turning off custom splash screen fixes the issue.

I already opened an issue on multiconnect's issue tracker and they said to come here.

**Comment by Motschen** [comment]
Can you see if this still occurs in customsplashscreen 2.0.0?

**Comment by DangerMage** [comment]
> Could you test if this still occurs in customsplashscreen 2.0.0?

I'll try later today if I remember

**Comment by DangerMage** [comment]
> > Could you test if this still occurs in customsplashscreen 2.0.0?
> 
> I'll try later today if I remember

Okay so, Multiconnect doesn't have a 1.19.4 version

(https://github.com/Earthcomputer/multiconnect#this-project-has-been-archived)

So i will test with viafabric plus

**Comment by DangerMage** [comment]
> > > Could you test if this still occurs in customsplashscreen 2.0.0?
> > 
> > 
> > I'll try later today if I remember
> 
> Okay so, Multiconnect doesn't have a 1.19.4 version
> 
> (https://github.com/Earthcomputer/multiconnect#this-project-has-been-archived)
> 
> So i will test with viafabric plus

Test complete. It works just fine.
