### ISSUE TITLE
1.21.3?

### ISSUE THREAD

**Issue by adamf30** [TeamMidnightDust/CustomSplashScreen#24]
The Bundles of Bravery drop has arrived, but for some reason I can't use this mod due to the changes.

**Comment by adamf30** [comment]
[latest.log](https://github.com/user-attachments/files/17608138/latest.log)

This log contains the crash issue.

**Comment by vinnyg0621** [comment]
same issue.

**Comment by Mine181** [comment]
Dev is busy with studies and had moved to a new city so expect slower updates, in the meantime you can use Controllify.

**Comment by adamf30** [comment]
> Dev is busy with studies and had moved to a new city so expect slower updates, in the meantime you can use Controllify.

I see, but Controllify is a different mod to this. This is for the Splash Screen.

**Comment by Mine181** [comment]
...I might've clicked a random 1.21.3 issue on the server without reading the github repository :p

**Comment by adamf30** [comment]
Looks like the mod is updated, so this issue can be closed.
